
DROP DATABASE IF EXISTS movilist;
CREATE DATABASE movilist;
USE movilist;

CREATE TABLE roles (
   id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(500)
);

CREATE TABLE genres (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(250)
);

CREATE TABLE status (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(250)
);

CREATE TABLE users (
   id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
   username VARCHAR(100),
   email VARCHAR(150) UNIQUE,
   password VARCHAR(1000),
   role_id INT DEFAULT 2 NOT NULL,
   CONSTRAINT FK_users_role_id FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

CREATE TABLE movies (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    title VARCHAR(250),
    description TEXT,
    release_date DATE,
    genre_id INT,
    image_url VARCHAR(250),
    CONSTRAINT FK_movies_genre_id FOREIGN KEY (genre_id) REFERENCES genres(id) ON DELETE CASCADE
);
